services:
  scraper:
    build: ./scraper
    volumes:
      - ./scraper:/app
    depends_on:
      - chrome

  chrome:
    image: selenium/standalone-chromium:latest
    ports:
      - "4444:4444"
    shm_size: 2gb
